from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class ZoektProtocol(Protocol):
    async def search_zoekt(self, **kwargs) -> list[dict[str, Any]]: ...
    async def search_regex(self, **kwargs) -> list[dict[str, Any]]: ...
    async def list_repos(self, **kwargs) -> list[dict[str, Any]]: ...
    async def fetch_file_content(self, repo: str, filepath: str, **kwargs) -> dict: ...
    async def health_check(self) -> bool | dict[str, bool]: ...
