#!/usr/bin/env python3
"""Generate deploy/docker-compose.yml from config/projects.yaml and .env.

This script is the single source of truth for compose generation. The output
file is a build artifact — do not edit it manually.

Usage:
    python scripts/generate_compose.py
    python scripts/generate_compose.py --projects-config config/projects.yaml --env-file .env
    python scripts/generate_compose.py --validate   # also run docker compose config
"""

import argparse
import os
import re
import subprocess
import sys
from pathlib import Path

import yaml

HEADER_COMMENT = (
    "# AUTO-GENERATED by scripts/generate_compose.py — DO NOT EDIT.\n"
    "# Source of truth: config/projects.yaml + .env\n"
    "# Regenerate: python scripts/generate_compose.py\n"
)

_VAR_RE = re.compile(r"\$\{([A-Za-z_][A-Za-z0-9_]*)(?::-(.*?))?\}")


def load_dotenv(path: Path) -> dict[str, str]:
    """Load a .env file, returning a dict of key-value pairs.

    Rules match scripts/share/_env.sh: skip blanks/comments, strip ``export``
    prefix, handle single/double quotes, strip inline comments on unquoted
    values.  Environment variables already set take precedence.
    """
    env: dict[str, str] = dict(os.environ)
    if not path.is_file():
        return env

    for raw_line in path.read_text().splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("export "):
            line = line[7:].lstrip()
        elif line.startswith("export\t"):
            line = line[7:].lstrip()

        if "=" not in line:
            continue
        key, _, value = line.partition("=")
        key = key.strip()
        if not re.fullmatch(r"[a-zA-Z0-9_]+", key):
            continue

        if (value.startswith('"') and value.endswith('"')) or (
            value.startswith("'") and value.endswith("'")
        ):
            value = value[1:-1]
        else:
            value = value.split("#")[0].rstrip()

        if key not in os.environ:
            env[key] = value

    return env


def expand(value: str, env: dict[str, str]) -> str:
    """Expand ``${VAR:-default}`` and ``${VAR}`` references in *value*."""

    def _replace(m: re.Match) -> str:
        var = m.group(1)
        default = m.group(2) if m.group(2) is not None else ""
        return env.get(var, default)

    return _VAR_RE.sub(_replace, value)


def expand_deep(obj: object, env: dict[str, str]) -> object:
    """Recursively expand variable references in a nested structure."""
    if isinstance(obj, str):
        return expand(obj, env)
    if isinstance(obj, dict):
        return {k: expand_deep(v, env) for k, v in obj.items()}
    if isinstance(obj, list):
        return [expand_deep(v, env) for v in obj]
    return obj


def load_projects(path: Path) -> list[dict]:
    """Load project definitions from projects.yaml."""
    with open(path) as f:
        data = yaml.safe_load(f)
    if not data or "projects" not in data:
        raise ValueError(f"Invalid projects config: 'projects' key missing in {path}")
    projects = data["projects"]
    if not isinstance(projects, list) or not projects:
        raise ValueError(f"'projects' must be a non-empty list in {path}")
    return projects


def _zoekt_service_template(volume_source: str, host_port: str) -> dict:
    return {
        "build": "./sparse/zoekt",
        "profiles": ["zoekt"],
        "volumes": [f"{volume_source}:/data/index:ro"],
        "ports": [f"{host_port}:6070"],
        "networks": ["sourcepilot-net"],
        "healthcheck": {
            "test": ["CMD", "curl", "-sf", "http://localhost:6070/"],
            "interval": "10s",
            "timeout": "5s",
            "retries": 5,
            "start_period": "120s",
        },
        "restart": "unless-stopped",
        "logging": {
            "driver": "json-file",
            "options": {"max-size": "10m", "max-file": "3"},
        },
    }


def build_zoekt_services(projects: list[dict], env: dict[str, str]) -> dict:
    """Generate one Zoekt service per project (or per sub-container for multi-Zoekt)."""
    services: dict[str, dict] = {}
    port_counter = 6070

    for idx, proj in enumerate(projects):
        name = proj["name"]
        sparse = proj.get("sparse_index", {})
        zoekt_urls = sparse.get("zoekt_urls")

        if isinstance(zoekt_urls, dict) and zoekt_urls:
            index_dirs = sparse.get("index_dirs", {})
            for sublabel in zoekt_urls:
                svc_name = f"sparse-index-zoekt-{name}-{sublabel}"
                env_key_path = f"ZOEKT_INDEX_PATH_{name.upper()}_{sublabel.upper()}"
                env_key_port = f"ZOEKT_PORT_{name.upper()}_{sublabel.upper()}"
                vol = env.get(env_key_path, index_dirs.get(sublabel, ""))
                port = env.get(env_key_port, str(port_counter))
                port_counter = max(port_counter, int(port)) + 1
                services[svc_name] = _zoekt_service_template(vol, port)
        else:
            svc_name = "sparse-index-zoekt" if idx == 0 else f"sparse-index-zoekt-{name}"
            env_key_path = f"ZOEKT_INDEX_PATH_{name.upper()}" if idx > 0 else "ZOEKT_INDEX_PATH"
            env_key_port = f"ZOEKT_PORT_{name.upper()}" if idx > 0 else "ZOEKT_PORT"
            default_path = sparse.get("index_dir", "")
            vol = env.get(env_key_path, default_path)
            port = env.get(env_key_port, str(port_counter))
            port_counter = max(port_counter, int(port)) + 1
            services[svc_name] = _zoekt_service_template(vol, port)

    return services


def _build_gateway_zoekt_env(projects: list[dict]) -> dict[str, str]:
    """Build ZOEKT_URL_* env vars for the gateway from project definitions."""
    zoekt_env: dict[str, str] = {}
    first_url = ""

    for idx, proj in enumerate(projects):
        name = proj["name"]
        sparse = proj.get("sparse_index", {})
        zoekt_urls = sparse.get("zoekt_urls")

        if isinstance(zoekt_urls, dict) and zoekt_urls:
            for sublabel in zoekt_urls:
                svc = f"sparse-index-zoekt-{name}-{sublabel}"
                url = f"http://{svc}:6070"
                zoekt_env[f"ZOEKT_URL_{name.upper()}_{sublabel.upper()}"] = url
                if not first_url:
                    first_url = url
        else:
            svc = "sparse-index-zoekt" if idx == 0 else f"sparse-index-zoekt-{name}"
            url = f"http://{svc}:6070"
            zoekt_env[f"ZOEKT_URL_{name.upper()}"] = url
            if not first_url:
                first_url = url

    zoekt_env["ZOEKT_URL"] = first_url
    return zoekt_env


def build_gateway_service(projects: list[dict], env: dict[str, str]) -> dict:
    gateway_env = {
        **_build_gateway_zoekt_env(projects),
        "PROJECTS_CONFIG_PATH": "/etc/sourcepilot/projects.yaml",
        "AUDIT_LOG_FILE": "/var/log/sourcepilot/audit.log",
        "AUDIT_ENABLED": env.get("AUDIT_ENABLED", "true"),
        "NL_ENABLED": env.get("NL_ENABLED", "false"),
        "NL_MODEL": env.get("NL_MODEL", ""),
        "NL_API_KEY": env.get("NL_API_KEY", ""),
        "NL_API_BASE": env.get("NL_API_BASE", ""),
        "DENSE_ENABLED": env.get("DENSE_ENABLED", "false"),
        "DENSE_VECTOR_DB_URL": "http://qdrant:6333",
        "DENSE_EMBEDDING_URL": "http://dense-index-coderankembed:8080/v1",
        "DENSE_EMBEDDING_MODEL": env.get("DENSE_EMBEDDING_MODEL", "unixcoder-base"),
        "DENSE_EMBEDDING_DIM": env.get("DENSE_EMBEDDING_DIM", "768"),
        "DENSE_COLLECTION_NAME": env.get("DENSE_COLLECTION_NAME", "aosp_code"),
        "STRUCTURAL_ENABLED": env.get("STRUCTURAL_ENABLED", "false"),
        "STRUCTURAL_NEO4J_URI": "bolt://neo4j:7687",
        "STRUCTURAL_NEO4J_USER": env.get("STRUCTURAL_NEO4J_USER", "neo4j"),
        "STRUCTURAL_NEO4J_PASSWORD": env.get("STRUCTURAL_NEO4J_PASSWORD", "sourcepilot"),
    }

    return {
        "build": {
            "context": "..",
            "dockerfile": "deploy/gateway/Dockerfile",
            "args": {
                "INSTALL_DENSE": env.get("GATEWAY_INSTALL_DENSE", "false"),
            },
        },
        "environment": gateway_env,
        "volumes": ["sourcepilot-audit:/var/log/sourcepilot"],
        "ports": [f"{env.get('SOURCEPILOT_PORT', '9000')}:9000"],
        "networks": ["sourcepilot-net"],
        "healthcheck": {
            "test": ["CMD", "curl", "-sf", "http://localhost:9000/api/health"],
            "interval": "30s",
            "timeout": "5s",
            "retries": 3,
            "start_period": "10s",
        },
        "restart": "on-failure:5",
        "logging": {
            "driver": "json-file",
            "options": {"max-size": "10m", "max-file": "3"},
        },
    }


def build_static_services(env: dict[str, str]) -> dict:
    """Build all non-Zoekt, non-gateway static services."""
    services: dict[str, dict] = {}

    services["zoekt-indexserver"] = {
        "build": "./sparse/zoekt",
        "entrypoint": ["zoekt-git-index"],
        "command": ["-index", "/data/index", "/data/repo/"],
        "volumes": [
            f"{env.get('ZOEKT_REPO_PATH', '/opt/aosp/aosp_project/.repo')}:/data/repo:ro",
            "zoekt_index:/data/index",
        ],
        "networks": ["sourcepilot-net"],
        "profiles": ["tools"],
    }

    services["sp-cockpit"] = {
        "build": "../sp-cockpit",
        "environment": {
            "SP_COCKPIT_AUDIT_LOG_PATH": "/var/log/sourcepilot/audit.log",
            "SP_COCKPIT_AUDIT_DB_PATH": "/data/audit.db",
        },
        "volumes": [
            "sourcepilot-audit:/var/log/sourcepilot:ro",
            "../sp-cockpit/data:/data",
        ],
        "ports": [f"{env.get('SP_COCKPIT_PORT', '9100')}:9100"],
        "depends_on": {
            "sourcepilot-gateway": {"condition": "service_started"},
        },
        "networks": ["sourcepilot-net"],
        "healthcheck": {
            "test": [
                "CMD",
                "python",
                "-c",
                "import urllib.request,sys;"  # noqa: E501
                " sys.exit(0 if urllib.request.urlopen("
                "'http://localhost:9100/api/health').status==200"
                " else 1)",
            ],
            "interval": "30s",
            "timeout": "5s",
            "retries": 3,
            "start_period": "120s",
        },
        "restart": "on-failure:5",
        "logging": {
            "driver": "json-file",
            "options": {"max-size": "10m", "max-file": "3"},
        },
    }

    services["mcp-server"] = {
        "build": {
            "context": "..",
            "dockerfile": "deploy/mcp/Dockerfile",
        },
        "environment": {
            "SOURCEPILOT_URL": env.get("SOURCEPILOT_URL", "http://sourcepilot-gateway:9000"),
            "MCP_AUTH_TOKEN": env.get("MCP_AUTH_TOKEN", ""),
        },
        "ports": [f"{env.get('MCP_PORT', '8888')}:8888"],
        "depends_on": {
            "sourcepilot-gateway": {"condition": "service_healthy"},
        },
        "networks": ["sourcepilot-net"],
        "healthcheck": {
            "test": ["CMD", "curl", "-sf", "http://localhost:8888/health"],
            "interval": "30s",
            "timeout": "5s",
            "retries": 3,
            "start_period": "10s",
        },
        "restart": "on-failure:5",
        "logging": {
            "driver": "json-file",
            "options": {"max-size": "10m", "max-file": "3"},
        },
    }

    services["qdrant"] = {
        "image": "qdrant/qdrant:v1.12.6",
        "volumes": ["qdrant_data:/qdrant/storage"],
        "ports": [
            f"{env.get('QDRANT_PORT', '6333')}:6333",
            f"{env.get('QDRANT_GRPC_PORT', '6334')}:6334",
        ],
        "ulimits": {"nofile": {"soft": 65536, "hard": 65536}},
        "healthcheck": {
            "test": ["CMD-SHELL", "bash -c '</dev/tcp/127.0.0.1/6333' || exit 1"],
            "interval": "10s",
            "timeout": "5s",
            "retries": 5,
            "start_period": "120s",
        },
        "networks": ["sourcepilot-net"],
        "restart": "unless-stopped",
    }

    services["dense-index-coderankembed"] = {
        "build": {"context": "./dense/embedding-server"},
        "environment": {
            "EMBEDDING_MODEL": env.get("EMBEDDING_MODEL", "microsoft/unixcoder-base"),
            "EMBEDDING_DIM": env.get("EMBEDDING_DIM", "768"),
            "HOST": "0.0.0.0",
            "PORT": "8080",
            "CODE_EMBEDDING_MODEL": env.get(
                "CODE_EMBEDDING_MODEL", "nomic-ai/CodeRankEmbed"
            ),
            "OMP_NUM_THREADS": env.get("OMP_NUM_THREADS", "4"),
            "ORT_INTER_OP_NUM_THREADS": env.get("ORT_INTER_OP_NUM_THREADS", "1"),
            "EMBEDDING_MAX_BATCH_SIZE": env.get("EMBEDDING_MAX_BATCH_SIZE", "256"),
        },
        "ports": [f"{env.get('EMBEDDING_PORT', '9088')}:8080"],
        "healthcheck": {
            "test": ["CMD", "curl", "-f", "http://localhost:8080/health"],
            "interval": "10s",
            "timeout": "5s",
            "retries": 5,
            "start_period": "60s",
        },
        "networks": ["sourcepilot-net"],
    }

    services["dense-indexer"] = {
        "build": {
            "context": "..",
            "dockerfile": "deploy/dense/indexer/Dockerfile",
        },
        "profiles": ["indexer"],
        "restart": "no",
        "depends_on": {
            "qdrant": {"condition": "service_healthy"},
            "dense-index-coderankembed": {"condition": "service_healthy"},
        },
        "environment": {
            "DENSE_VECTOR_DB_URL": "http://qdrant:6333",
            "DENSE_EMBEDDING_URL": "http://dense-index-coderankembed:8080/v1",
            "DENSE_EMBEDDING_MODEL": env.get("DENSE_EMBEDDING_MODEL", "unixcoder-base"),
            "DENSE_EMBEDDING_DIM": env.get("DENSE_EMBEDDING_DIM", "768"),
            "DENSE_COLLECTION_NAME": env.get("DENSE_COLLECTION_NAME", "aosp_code"),
            "PROJECTS_CONFIG_PATH": "/config/projects.yaml",
            "EMBEDDING_BATCH_SIZE": env.get("EMBEDDING_BATCH_SIZE", "128"),
            "EMBEDDING_CONCURRENCY": env.get("EMBEDDING_CONCURRENCY", "32"),
            "EMBEDDING_MAX_CONNECTIONS": env.get("EMBEDDING_MAX_CONNECTIONS", "64"),
            "EMBEDDING_MAX_KEEPALIVE": env.get("EMBEDDING_MAX_KEEPALIVE", "32"),
        },
        "volumes": [
            f"{env.get('AOSP_SOURCE_ROOT', '/opt/aosp/aosp_project')}:/src:ro",
            "../config:/config:ro",
        ],
        "networks": ["sourcepilot-net"],
    }

    services["neo4j"] = {
        "image": "neo4j:5-community",
        "container_name": "sourcepilot-neo4j",
        "restart": "unless-stopped",
        "ports": ["7474:7474", "7687:7687"],
        "environment": {
            "NEO4J_AUTH": "neo4j/sourcepilot",
            "NEO4J_PLUGINS": '["apoc"]',
            "NEO4J_server_memory_heap_initial__size": "1G",
            "NEO4J_server_memory_heap_max__size": "4G",
            "NEO4J_server_memory_pagecache_size": "2G",
        },
        "volumes": [
            "neo4j_data:/data",
            "neo4j_logs:/logs",
            "neo4j_import:/var/lib/neo4j/import",
            "neo4j_plugins:/plugins",
        ],
        "healthcheck": {
            "test": [
                "CMD",
                "cypher-shell",
                "-u",
                "neo4j",
                "-p",
                "sourcepilot",
                "RETURN 1",
            ],
            "interval": "30s",
            "timeout": "10s",
            "retries": 5,
            "start_period": "40s",
        },
        "networks": ["sourcepilot-net"],
    }

    services["structural-indexer"] = {
        "build": {
            "context": "..",
            "dockerfile": "deploy/structural/indexer/Dockerfile",
        },
        "profiles": ["indexer"],
        "restart": "no",
        "depends_on": {
            "neo4j": {"condition": "service_healthy"},
        },
        "environment": {
            "STRUCTURAL_NEO4J_URI": "bolt://neo4j:7687",
            "STRUCTURAL_NEO4J_USER": env.get("STRUCTURAL_NEO4J_USER", "neo4j"),
            "STRUCTURAL_NEO4J_PASSWORD": env.get(
                "STRUCTURAL_NEO4J_PASSWORD", "sourcepilot"
            ),
        },
        "volumes": [
            f"{env.get('AOSP_SOURCE_ROOT', '/opt/aosp/aosp_project')}:/src:ro",
            "../config:/config:ro",
        ],
        "networks": ["sourcepilot-net"],
    }

    return services


def generate(projects: list[dict], env: dict[str, str]) -> dict:
    """Build the complete compose dict."""
    zoekt_services = build_zoekt_services(projects, env)
    gateway = build_gateway_service(projects, env)
    static = build_static_services(env)

    services = {}
    services.update(zoekt_services)
    services["zoekt-indexserver"] = static.pop("zoekt-indexserver")
    services["sourcepilot-gateway"] = gateway
    for svc_name in [
        "sp-cockpit",
        "mcp-server",
        "qdrant",
        "dense-index-coderankembed",
        "dense-indexer",
        "neo4j",
        "structural-indexer",
    ]:
        services[svc_name] = static[svc_name]

    return {
        "name": "sourcepilot",
        "services": services,
        "networks": {
            "sourcepilot-net": {
                "name": "sourcepilot-net",
                "driver": "bridge",
            },
        },
        "volumes": {
            "zoekt_index": None,
            "qdrant_data": None,
            "neo4j_data": None,
            "neo4j_logs": None,
            "neo4j_import": None,
            "neo4j_plugins": None,
            "sourcepilot-audit": None,
        },
    }


def is_stale(output: Path, projects_config: Path, env_file: Path) -> bool:
    """Return True if the output file is older than either input."""
    if not output.exists():
        return True
    out_mtime = output.stat().st_mtime
    for src in (projects_config, env_file):
        if src.exists() and src.stat().st_mtime > out_mtime:
            return True
    return False


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--projects-config",
        default="config/projects.yaml",
        help="Path to projects.yaml (default: config/projects.yaml)",
    )
    parser.add_argument(
        "--env-file",
        default=".env",
        help="Path to .env file (default: .env)",
    )
    parser.add_argument(
        "--output",
        default="deploy/docker-compose.yml",
        help="Output path (default: deploy/docker-compose.yml)",
    )
    parser.add_argument(
        "--validate",
        action="store_true",
        help="Run docker compose config after generation",
    )
    parser.add_argument(
        "--check-stale",
        action="store_true",
        help="Only warn if output is stale, do not regenerate",
    )
    args = parser.parse_args(argv)

    projects_path = Path(args.projects_config)
    env_path = Path(args.env_file)
    output_path = Path(args.output)

    if args.check_stale:
        if is_stale(output_path, projects_path, env_path):
            print(
                f"WARNING: {output_path} is stale — regenerate with: "
                f"python scripts/generate_compose.py",
                file=sys.stderr,
            )
            return 1
        return 0

    env = load_dotenv(env_path)
    projects = load_projects(projects_path)
    compose = generate(projects, env)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    content = HEADER_COMMENT + yaml.dump(
        compose, default_flow_style=False, sort_keys=False, allow_unicode=True
    )
    output_path.write_text(content)
    print(f"Generated {output_path} ({len(projects)} project(s))", file=sys.stderr)

    if args.validate:
        result = subprocess.run(
            ["docker", "compose", "-f", str(output_path), "config", "-q"],
            capture_output=True,
            text=True,
        )
        if result.returncode != 0:
            print(f"Validation FAILED:\n{result.stderr}", file=sys.stderr)
            return 1
        print("Validation passed (docker compose config)", file=sys.stderr)

    return 0


if __name__ == "__main__":
    sys.exit(main())
